SOURCEPATH = MAPR/src/ds/hdfs
CLASSPATH = MAPR/bin/

all:
	javac -d $(CLASSPATH) -sourcepath $(SOURCEPATH) temporaryInterface.java 
	javac -d $(CLASSPATH) -cp $(CLASSPATH) -sourcepath $(SOURCEPATH) NetworkTest.java 
clean:
	rm -rf $(CLASSPATH)ds
